File I/O: Implement game data saving & loading (C++17 `std::filesystem`) (#47)
* Loading and Saving gameplay data

* can save game status but not load currently

* save file go flawlessly with c++17 functions, load funcion segfault

* there is segfault in stock.cpp row 56

* Compilation successful

* Bug: Fix SEGFAULT due to uninitialized stocks_list <stock> objects

* Remove Apple unrelated files

* Files can io properly now without events

graph can be plot with correct input of (stock no. in UI - 1)

* Run clang-format

make fix

* Implement operator>> operator<< serializer and deserializer for Stock_event data type

* Run clang-format

make fix

* loading events and fix stock.random

* Finished event loading

* Run clang-format

* Remove useless text from makefile

* bug fix when player trying to load save with save

comments added

* Resolve “shutup compiler”

I just want better formatted functions without compiler spitting warnings

* Fix indentation

ipad editor sucks

* ;

;

* Fix draw.cpp:36:10: error: ‘ignore’ is not a member of ‘std’

* Temporary fix for make test hanging

* Disable the make test check. No idea why it runs indefinitely

* fix

---------

Co-authored-by: Cheng Ho Ming, Eric <eric310@connect.hku.hk>
Co-authored-by: Prismatiscence <56928422+Prismatiscence@users.noreply.github.com>